import type { Project, Status } from "./types.ts";
import { categoryOrder } from "./classify.ts";

export const STATUS_META: Record<Status, { emoji: string; label: string; meaning: string }> = {
  active: { emoji: "🟢", label: "Active", meaning: "Worked on recently (roughly the last ~6 weeks)" },
  paused: { emoji: "🟡", label: "Paused", meaning: "Real project, currently idle — picks back up later" },
  library: { emoji: "📦", label: "Library", meaning: "Reusable package; maintained, not actively built" },
  utility: { emoji: "🔵", label: "Utility", meaning: "Small supporting tool that just works" },
  experiment: { emoji: "⚪", label: "Experiment", meaning: "Early, minimal, or a parked idea" },
  planning: { emoji: "🗒️", label: "Planning", meaning: "Roadmap / notes, not a codebase" },
  archived: { emoji: "🗄️", label: "Archived", meaning: "Superseded version, demo, or template" },
};

function anchor(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

export function renderMarkdown(projects: Project[]): string {
  const now = new Date().toISOString().slice(0, 10);
  const active = projects.filter((p) => !p.archived);
  const archived = projects.filter((p) => p.archived);

  const out: string[] = [];
  out.push("# Projects Rundown");
  out.push("");
  out.push(
    "_Generated by **psm** — do not hand-edit; run `npm run build:md` or export from the dashboard._",
  );
  out.push("");
  out.push(`**Last generated:** ${now}`);
  out.push("");

  // legend
  out.push("### Status legend");
  out.push("");
  out.push("| | Meaning |");
  out.push("|---|---|");
  for (const s of ["active", "paused", "library", "utility", "experiment", "planning", "archived"] as Status[]) {
    out.push(`| ${STATUS_META[s].emoji} **${STATUS_META[s].label}** | ${STATUS_META[s].meaning} |`);
  }
  out.push("");
  out.push("---");
  out.push("");

  // at a glance
  out.push("## At a glance");
  out.push("");
  out.push("| Project | Status | What it is | Stack | Last activity | Branch / ver |");
  out.push("|---|---|---|---|---|---|");
  for (const p of active) {
    const m = STATUS_META[p.status];
    const ver = [p.gitBranch && `\`${p.gitBranch}\``, p.gitVersion && `\`${p.gitVersion}\``]
      .filter(Boolean)
      .join(" ") || "—";
    out.push(
      `| [${p.name}](#${anchor(p.name)}) | ${m.emoji} ${m.label} | ${short(p.description)} | ${p.stack} | ${p.lastActivity || "—"} | ${ver} |`,
    );
  }
  out.push("");
  out.push("---");
  out.push("");

  // full cards grouped by category
  const cats = [...new Set(active.map((p) => p.category))].sort(
    (a, b) => categoryOrder(a) - categoryOrder(b),
  );
  for (const cat of cats) {
    out.push(`## ${cat}`);
    out.push("");
    for (const p of active.filter((x) => x.category === cat)) {
      const m = STATUS_META[p.status];
      out.push(`### ${p.name}`);
      out.push(`${m.emoji} **${m.label}**${p.priority ? ` · priority: ${p.priority}` : ""}${p.pinned ? " · 📌 pinned" : ""}`);
      out.push("");
      out.push(p.description);
      out.push("");
      out.push(`- **Stack:** ${p.stack}`);
      const ver = [p.gitBranch && `branch \`${p.gitBranch}\``, p.gitVersion && `\`${p.gitVersion}\``]
        .filter(Boolean)
        .join(" · ");
      out.push(
        `- **Last activity:** ${p.lastActivity || "—"}${p.lastActivitySource === "files" ? " (file mtime, no git)" : ""}${ver ? " · " + ver : ""}`,
      );
      if (p.next) out.push(`- **Next:** ${p.next}`);
      out.push("");
    }
    out.push("---");
    out.push("");
  }

  // archived table
  out.push("## 🗄️ Archived · demos · templates");
  out.push("");
  out.push(
    "Older versions, superseded builds, demos, and templates. Kept for reference; not actively maintained.",
  );
  out.push("");
  out.push("| Folder | What it is | Last touched |");
  out.push("|---|---|---|");
  for (const p of archived) {
    out.push(`| ${p.name} | ${short(p.note || p.description)} | ${p.lastActivity || "—"} |`);
  }
  out.push("");

  return out.join("\n") + "\n";
}

function short(s: string, max = 90): string {
  const clean = s.replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();
  return clean.length > max ? clean.slice(0, max - 1) + "…" : clean;
}
